using System;
using System.Collections.Generic;

namespace TSL.Data.Models.Comarch_BI_TEST_REPO;

public partial class BudgetVersion
{
    public int Id { get; set; }

    /// <summary>
    /// One2ManyCascade=all-delete-orphan;One2ManyInverse=true;Many2OneCascade=none;
    /// </summary>
    public int BudgetId { get; set; }

    public string? Name { get; set; }

    public int RowVer { get; set; }

    public string State { get; set; } = null!;

    public bool AllowRejectParentEntries { get; set; }

    /// <summary>
    /// One2Many=false;Many2OneCascade=none;
    /// </summary>
    public int CreationUserId { get; set; }

    public DateTime CreationDate { get; set; }

    public DateTime? LoadDate { get; set; }

    public bool TreadBudget { get; set; }

    public byte[]? ExcelBinaryData { get; set; }

    public string? ExcelFileName { get; set; }

    public bool? OpenInExcel { get; set; }

    public bool HasAutogeneratedSums { get; set; }

    public virtual Budget Budget { get; set; } = null!;

    public virtual ICollection<BudgetColumn> BudgetColumns { get; set; } = new List<BudgetColumn>();

    public virtual ICollection<BudgetEntry> BudgetEntries { get; set; } = new List<BudgetEntry>();

    public virtual BudgetVersionChange? BudgetVersionChange { get; set; }

    public virtual ICollection<BudgetVersionCubesPermission> BudgetVersionCubesPermissions { get; set; } = new List<BudgetVersionCubesPermission>();

    public virtual User1 CreationUser { get; set; } = null!;

    public virtual ICollection<Permission> Permissions { get; set; } = new List<Permission>();

    public virtual ICollection<TimeMember> TimeMembers { get; set; } = new List<TimeMember>();
}
